package eu.kryocloud.common.config.type;

import java.io.BufferedWriter;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Properties;

public class PropertiesTypeProvider extends TypeProvider {

    @Override
    public void load(Path file) throws Exception {
        data.clear();
        if (!Files.exists(file)) return;

        Properties properties = new Properties();

        try (InputStream in = Files.newInputStream(file)) {
            properties.load(in);
        }

        for (String key : properties.stringPropertyNames()) {
            String value = properties.getProperty(key);
            data.put(key, value);
        }
    }

    @Override
    public <T> void save(Path file, T config) throws Exception {
        Map<String, Object> values = data;
        Map<String, String[]> comments = java.util.Map.of();

        if (config != null) {
            var encoded = encodeConfig(file, config);
            values = encoded.flatData();
            comments = encoded.comments();
        }

        if (file.getParent() != null) {
            Files.createDirectories(file.getParent());
        }

        try (BufferedWriter writer = Files.newBufferedWriter(file, StandardCharsets.UTF_8)) {
            writer.write("# Generated by KryoCloud");
            writer.newLine();

            for (Map.Entry<String, Object> entry : values.entrySet()) {
                String[] fieldComments = comments.get(entry.getKey());

                if (fieldComments != null) {
                    for (String comment : fieldComments) {
                        writer.write("# ");
                        writer.write(comment);
                        writer.newLine();
                    }
                }
                writer.write(escape(entry.getKey(), true));
                writer.write('=');
                writer.write(escape(String.valueOf(entry.getValue()), false));
                writer.newLine();
            }
        }
    }

    private String escape(String value, boolean key) {
        StringBuilder builder = new StringBuilder(value.length());

        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);

            switch (c) {
                case '\\' -> builder.append("\\\\");
                case '\t' -> builder.append("\\t");
                case '\n' -> builder.append("\\n");
                case '\r' -> builder.append("\\r");
                case '\f' -> builder.append("\\f");
                case ' ' -> {
                    if (i == 0 || key) {
                        builder.append("\\ ");
                    } else {
                        builder.append(c);
                    }
                }
                case '=', ':', '#', '!' -> builder.append('\\').append(c);
                default -> builder.append(c);
            }
        }

        return builder.toString();
    }
}